language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry config virtualenvs.create false
  - poetry install --verbose

script:
  - poetry run black --check .
  - poetry run pytest -vvv tests

notifications:
  email: false